[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tvp = "6srUu57dvG9XpgcfxJGp3yR2Pg6dDZzc2F4Aydwns5gv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
